apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: demo
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: go-server:v1
    env:
    - name: NAME
      value: ENICarthage