apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: demo
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: go-server:v1
    env:
    - name: NAME
      value: ENICarthage
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 1h"]