apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: mysecret
      containers:
      - name: go-server
        image: go-server:v1
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: myconfig
        #         key: NAME
        envFrom:
          - configMapRef:
              name: myconfig
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /var/secrets
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server